name: Run tests

# Run for each push to a PR and also when a PR is merged to master.
on: [pull_request, push]

jobs:

  # Docs build job:
  build-docs:
    name: Build the docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install sphinx
        run: pip install sphinx

      - name: Build docs
        working-directory: ./doc
        run: make html

        # This makes the doc zip available from GitHub on a PR before the PR
        # is merged. I'm not sure yet if that is a good idea. Apparently
        # github "bills" for this storage but I don't know what impact that
        # has for non-paying public open source repos.
        #
        # It also makes it possible to share the built docs from this job to
        # the deploy job. It is not strictly necessary for that though as the
        # deploy job could really just be a conditional step in this job.
      - name: Attach docs artifact
        uses: actions/upload-artifact@v2
        with:
          name: htmldocs
          path: doc/build/html

  # Docs deploy job
  deploy-docs:
    name: Deploy the docs
    runs-on: ubuntu-latest

    # Only run this job on the master branch (after a PR is merged but not
    # when the PR is pushed to).
    if: github.ref == 'refs/heads/master'

    # Wait for docs to build before dploying them!
    needs: build-docs

    steps:
      - uses: actions/checkout@v2

        # Download the previously uploaded docs that were built
      - uses: actions/download-artifact@v2
        with:
          name: htmldocs

      - run: ls html

          #- uses: peaceiris/actions-gh-pages@v3
          # with:
      #github_token: ${{ secrets.GITHUB_TOKEN }}
      #publish_dir: ./public
